common: &COMMON
  adapter: postgresql
  username: damienkan
  pool: 5

development:
  <<: *COMMON
  database: webhooks_dev
  host: localhost

test:
  <<: *COMMON
  database: webhooks_test
  host: localhost

production:
  <<: *COMMON
  database: webhooks_prod
  password:
